### ISSUE TITLE
[Bug report] Crash when trying to make a screenshot

### ISSUE THREAD

**Issue by krater** [Pyrdacor/Ambermoon.net#334] opened 2022-12-03 17:04 UTC
**Describe the bug**
Observed on Ambermoon.net V1.7.1, Ambermoon Advanced 0.01 German on Windows 7.
Ambemoon.net is in Window-Mode.
1) Load game
2) Press 'Print'-Button on Keyboard to make a screenshot. 
![ambercrash](https://user-images.githubusercontent.com/151824/205452780-8137c05f-3fc7-44b8-83b0-ef7bab127d6b.png)

Console prints Stacktrace and Gams crashes.

**Comment by Pyrdacor** [comment] 2022-12-05 15:56
The error code means "Internal CLR error". So this can mean a lot and is not related to the game code I guess but more likely to be caused by something on your system. Can you try to check if the installation folder has write access?

**Comment by krater** [comment] 2022-12-05 17:07
Yes, I can write to the installation folder. Good old Win7 without any security/'dumb user'-features activated. Have added new text-file and changed the config by hand. 
What I don't understand is, why Ambermoon reacts on the 'Print'-Key because this should be the job of Windows. The screenshot is created from Windows, but then Ambermoon is dead.

**Comment by Pyrdacor** [comment] 2022-12-05 17:12
I could remove the print screen key and just stick to Ctrl+P for the internal screenshot feature.

**Comment by krater** [comment] 2022-12-05 17:20
![Screenshot_05-12-2022 18-12-59](https://user-images.githubusercontent.com/151824/205701446-9bbf87c9-52bb-4dd5-a5d6-320f0d3444ad.png)

**Comment by krater** [comment] 2022-12-05 17:22
Maybee my config-file will help.
[ambermoon.txt](https://github.com/Pyrdacor/Ambermoon.net/files/10156417/ambermoon.txt)
Renamed from cfg to txt because github.

**Comment by Pyrdacor** [comment] 2022-12-05 17:22
I think the internal screenshot functionality is only used after the game starts. So here you have the Windows screenshot. As it is an OpenGL window, this might cause those strange effects.

**Comment by Pyrdacor** [comment] 2022-12-05 17:24
Can you try to copy the main exe into a new directory inside your user or temp path and start it there? I know that the programs folder has some limitations.

**Comment by Pyrdacor** [comment] 2022-12-05 17:24
Just to rule out any permission issues

**Comment by krater** [comment] 2022-12-05 17:59
I copied only the exe to my user folder, so the game started from new. As I was in the place where I can walk around the house I pressed print and the game died again. So I would suppose its not a configuration issue and not a permission issue.

But does OpenGL has anything to do with the screenshot-feature that could lead to this?

**Comment by krater** [comment] 2022-12-05 18:03
> I could remove the print screen key and just stick to Ctrl+P for the internal screenshot feature.

Now I know that it works when the Window doesn't have the focus I don't really need a workaround like this. But maybee we find the reason and can fix it.

**Comment by krater** [comment] 2022-12-05 18:08
> I think the internal screenshot functionality is only used after the game starts. So here you have the Windows screenshot. As it is an OpenGL window, this might cause those strange effects.

No, this is the Ambermoon-Screenshot I found in the Ambermoon.net/screenshots-folder. 
The other one only lands in the clipboard until I paste it to Paint and save it.

**Comment by Pyrdacor** [comment] 2022-12-05 18:46
Ok thanks for your investigation. I will try to reproduce and fix this tomorrow.

**Comment by Pyrdacor** [comment] 2022-12-05 18:47
What is your desktop resolution and did you try to make a screenshot in fullscreen mode too?

**Comment by krater** [comment] 2022-12-05 22:46
I'm working with 1920x1080 and 1920x1200, same result. I have 3 screens on my docking station but the problem happend too when the notebook is undocked and on one screen with 1920x1080. I will try it at fullscreen mode.

**Comment by krater** [comment] 2022-12-05 22:49
Fullscreen mode doesn't works at all, I only get a black screen. And when I press the print-button it crashes. I don't know if with the same stacktrace because I can't see the console window.

**Comment by krater** [comment] 2022-12-05 22:51
When I can help in any way let it me know.

**Comment by Pyrdacor** [comment] 2022-12-06 04:35
According to some sites on the web the error code is related to a corruption of the garbage collector which happens when memory is somehow manipulated in an unsafe way. The only thing I can think of in this case is the actual read of the pixels from OpenGL.

When you try to make the screenshot, are you on a 2D or 3D map? Can you check the other map type? Also try to make a screenshot from the inventory or some other window please.

And then the effect shader has an influence so try to enable effects like sepia or grayscale and then try to make a screenshot.

If everything crashes it is most likely due to some resolution issue or some setting in Windows. Maybe some scaling/dpi setting?

**Comment by krater** [comment] 2022-12-06 06:55
It happens on 2D, 3D, inventory, with Sepia and Greyscale. The scaling is on 100%, 96ppi, what Windows means is standard, but I think it was 125% on installation.
I'm using Windows 7 in the classic mode, Aero is disabled.

**Comment by Pyrdacor** [comment] 2022-12-06 12:39
It works fine on my end. Also Win7 and I also tried the classic mode.

If the fullscreen mode isn't working at all, I almost would assume that your graphic driver has an issue. This can also be the cause for the screenshot problem. Do you have the latest drivers installed? You can also try to install glfw manually in addition as this is the underlying Windowing system.

**Comment by krater** [comment] 2022-12-13 21:36
Sorry, currently not much time for long tests. I installed some month ago the newest graphics card driver, but maybee there are some other components that could be older. Have no problems with other games or windows software that uses 3d rendering. But didn't tested much, just some 3d printer slicer and Age Of Empires III.
Will update this when I have more time.
When no one else has this issue, you can close the ticket, then its a problem on my side.

**Comment by Pyrdacor** [comment] 2023-03-27 12:36
Ok I found the issue and already fixed it. Will be part of next release.

**Closed** 2023-08-14 22:12 UTC
Labels: bug, fixed in code or data
