### ISSUE TITLE
[Bug Report] Enemies get stuck in second lowest row

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#364] opened 2023-12-23 10:56 UTC
**Describe the bug**
When an enemy enters the second lowest row, he seems to be unable to move.

**To Reproduce**
1. Put the player character in the rightmost position of the front row, Egil next to them
2. Start combat with the bandit + bandit captain
3. Click on okay. The leftmost bandit moves into the second lowest row
4. Click on okay. The leftmost bandit stays where he was in the round before, although a route to Egil is valid
5. Kill the central bandit next to Egil (e.g. Firebrand)
6. Click on okay. The leftmost bandit still remains (even though now a route in the second and third row is available)

**Expected behavior**
The bandit should use the path in the second row to move to Egil. If he cannot move horizontally in the second row, he should return to the third row and move to Egil as soon as the place next to him is free.

**Screenshots**
Movements during combat.
![image](https://github.com/Pyrdacor/Ambermoon.net/assets/88923192/30152d1b-5169-4c76-bd48-a551326c307d)
![image](https://github.com/Pyrdacor/Ambermoon.net/assets/88923192/80261b82-e8d1-4281-80e2-904e104bc1a3)
![image](https://github.com/Pyrdacor/Ambermoon.net/assets/88923192/6dcc7405-eba4-40b5-b3fb-195702846b4a)
After Fireball:
![image](https://github.com/Pyrdacor/Ambermoon.net/assets/88923192/45fc2799-b3f5-4e7c-9c5e-1ea061909175)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
I'm using ambermoon advanced (1.03) and ambermoon 1.9.2. The attached Save 2 has the appropriate setup, simply clicking okay during combat should create the situation described in the bug.

**Comment by Pyrdacor** [comment] 2023-12-27 00:50
This should be fixed in 1.9.3 now.

**Comment by Pyrdacor** [comment] 2023-12-27 00:51
Note that the bandit will still not move up and right if another bandit blocks the horizontal way. This is on purpose for now and not a bug. More a missing feature. ;)

**Closed by Pyrdacor** 2023-12-27 00:50 UTC
Labels: bug
