### ISSUE TITLE
Ambermoon.net leaves lots of temporary files

### ISSUE THREAD

**Issue by kermitfrog** [Pyrdacor/Ambermoon.net#205] opened 2021-09-19 19:42 UTC
trying to get AmbermoonPack to work, I just noticed that I have ~1.1GB of files in `~/.net/Ambermoon.net` and `/var/tmp/.net/`.
These seem to be .NET libraries - probably one directory of them for every version of the standalone version of Ambermoon.net that was ever installed.

It would be great if that stuff would be cleaned up or at least not duplicated for every version.

I'm experiencing this on linux, but assume the same will happen at least on macOS...

**Comment by Pyrdacor** [comment] 2021-09-19 19:52
The standalone executable is nothing more than a kind of self-extracting archive. When you execute it, it copies all the files in it to some temp directory and runs the real exe from there. It contains many libraries that are necessary to run. This is some .NET functionality. I am not aware of some automatic cleanup. But I wonder why this should happen for each version. In general it should replace the files. Only if there are new dependencies that could happen.

Anyway I will have a look if this can be reverted somehow.

**Comment by Pyrdacor** [comment] 2021-09-19 19:54
I hope that .NET Native or something similar will become a stable thing for xplat. Then I could compile to os-specific programs and avoid the whole NET dependency stuff.

**Comment by kermitfrog** [comment] 2021-09-19 20:39
> The standalone executable is nothing more than a kind of self-extracting archive. When you execute it, it copies all the files in it to some temp directory and runs the real exe from there. [..]

Yeah, I thought so... 
Inside `~/.net/Ambermoon.net` I have several subdirectories, named 
```
0ukki4kz.mgr  jwimsp30.jqr  k13xkxeb.14z  ktjtayad.mo0  s5zruepi.4h2  u5diozwl.l4i  yiidcwil.ztg
```
I assume these are some kind of checksum on the some propertie of the archive. Each contains pretty much the same ~78 MB of files. These are doubled in /var/tmp/.net/ - but with different names.

The best sollution seems to me, to create these files inside a subdirectory the application directory (from where the standalone executable is started), also containing a simple textfile with that checksum - that should ensure they are overwritten on upgrade and deleted on uninstall.
Maybe you can find a way to do that.

> I hope that .NET Native or something similar will become a stable thing for xplat. Then I could compile to os-specific programs and avoid the whole NET dependency stuff.

I looked up xplat, but am not sure I understand what it is. It sounds like a layer that maps a interpreted framework to native libraries.. I'm very sceptic about how well this would work for something as complex as .NET

**Comment by Pyrdacor** [comment] 2021-09-19 20:50
> The best sollution seems to me, to create these files inside a subdirectory the application directory (from where the standalone executable is started), also containing a simple textfile with that checksum - that should ensure they are overwritten on upgrade and deleted on uninstall.

The problem is that this is automatically done by .NET and I have no control over it. I could maybe come up with some custom solution where I create a similar package but it might be a bit of work.

> > I hope that .NET Native or something similar will become a stable thing for xplat. Then I could compile to os-specific programs and avoid the whole NET dependency stuff.
> 
> I looked up xplat, but am not sure I understand what it is. It sounds like a layer that maps a interpreted framework to native libraries.. I'm very sceptic about how well this would work for something as complex as .NET

Sorry, with xplat I just meant "cross platform". .NET uses an intermediate language like Java. That's why you need the .NET runtime. .NET Native was added to create native machine code like C++ compilers do. But unfortunately it only worked for UWP applications (and therefore Windows only). So I wait for a way to compile to native code for all kind of platforms. Maybe .NET6 will finally offer something like it but I doubt it.

**Comment by Pyrdacor** [comment] 2021-09-27 07:30
I decided to update from .NET Core 3.1 to .NET 5. This way the executable will no longer extract temp files. This is already pushed to the repo and will be part of Ambermoon.net 1.2.

**Comment by Pyrdacor** [comment] 2021-09-30 16:24
Hm I reverted the changes. .NET5 allows real single files but it won't pack native dependecies into it. As I need glfw and openal libs, this won't work. I think I might add some cleanup code myself.

**Comment by Pyrdacor** [comment] 2021-09-30 17:11
The temp files for the same executable version (not 1.1 etc but really the same data) are stored in the same directory and can be reused.

I added some cleanup code which deletes as much files from own temp file folder (not all is possible as the executable is still running and I don't want to mess with post-executed scripts etc). Moreover it will delete parallel temp folders (of course also inside the Ambermoon.net sub-folder). So new versions will clean up the temp dirs of other versions and also clean up their own folder a bit on termination.

**Closed** 2021-10-07 09:03 UTC
Labels: enhancement, fixed in code, v1.2
