### ISSUE TITLE
[Feature Request] Original Aspect Ratio

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#69] opened 2021-02-02 18:25 UTC
I have a small feature request. It would be nice if the correct Amiga Ascpect Ratio could be set as the standard resolution stretches the Games screen which looks ugly especially in fullscreen.

**Comment by Pyrdacor** [comment] 2021-02-02 20:51
Should be the default already. Wasn't it 320x200 (16:10)?

I used 4:3 by mistake a while ago as default, maybe it's still saved in your config? You can change the screen ratio and resolution in the option menu easily.

**Comment by Thallyrion** [comment] 2021-02-02 22:05
Just wanted to check the options as i had not seen that aspect there and to my surprise i now get this crash at startup

Object reference not set to an instance of an object.
   at Ambermoon.GameWindow.WindowMoved()
   at Ambermoon.GameWindow.Window_Move(Point position)
   at Silk.NET.Windowing.Desktop.GlfwWindow.<InitializeCallbacks>b__145_0(WindowHandle* window, Int32 x, Int32 y)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Ambermoon.GameWindow.WindowMoved()
   at Ambermoon.GameWindow.Window_Move(Point position)
   at Silk.NET.Windowing.Desktop.GlfwWindow.<InitializeCallbacks>b__145_0(WindowHandle* window, Int32 x, Int32 y)

**Comment by Pyrdacor** [comment] 2021-02-02 22:30
Yeah I found that bug today too. Fixed it already. Comes with the next release. The problem is the fullscreen setting. It will cause the crash on startup. You have to disable fullscreen manually in config to avoid the crash. :(

**Comment by Pyrdacor** [comment] 2021-02-03 16:01
Crash should be fixed in 0.2.2beta. And you were right. Default setting was indeed 4:3. Changed it to 16:10 as well.

**Closed** 2021-02-03 19:38 UTC
