### ISSUE TITLE
Sprite Bug on 2D Map

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#38] opened 2020-09-16 15:23 UTC
I noticed the following bug:
![sprite bug](https://user-images.githubusercontent.com/69513157/93358071-58869880-f841-11ea-8e05-ad6d02b0827e.png)
![sprite bug2](https://user-images.githubusercontent.com/69513157/93358202-7e13a200-f841-11ea-86d1-2448d9cb0ed8.png)

should look like this:
![original](https://user-images.githubusercontent.com/69513157/93358540-e6fb1a00-f841-11ea-87d5-c4a88014438c.png)

**Comment by Pyrdacor** [comment] 2020-09-16 16:15
Damn I thought I fixed it already. Which version did you try?

**Comment by Thallyrion** [comment] 2020-09-16 16:31
1.15

**Comment by Pyrdacor** [comment] 2020-09-16 17:11
Ok I will check tomorrow.

**Comment by Pyrdacor** [comment] 2020-09-17 06:53
I can't reproduce this in 1.1.5. How did you do it?

**Comment by Thallyrion** [comment] 2020-09-17 12:54
I made a video showing it

https://drive.google.com/file/d/1g7koZb2zqzUcV2RJjnpBXJC4PfwV1Fu-/view?usp=sharing

**Comment by Thallyrion** [comment] 2020-09-17 14:25
1.17 did not fix it. I just tried it. same spot.

![sprite bug3](https://user-images.githubusercontent.com/69513157/93484642-75cf6b80-f902-11ea-9828-8f8c474fd12a.png)

**Comment by Pyrdacor** [comment] 2020-09-17 14:47
Ok this is caused when you don't move and only the direction is changed. I will fix this tomorrow. :)

**Comment by Pyrdacor** [comment] 2020-09-18 09:12
Should be fixed in v1.1.8.

**Comment by Thallyrion** [comment] 2020-09-19 09:35
Yes it is fixed

**Comment by Pyrdacor** [comment] 2020-09-21 15:21
Ok I could reproduce this and fixed it. Will be available in next release. :)

**Comment by Pyrdacor** [comment] 2020-09-21 15:55
Should be fixed in 1.1.9

**Closed by Pyrdacor** 2020-09-21 15:55 UTC
Labels: bug
