### ISSUE TITLE
Game freezes when using spells against Gizzeks in Dorina's tree

### ISSUE THREAD

**Issue by HptmKarotte** [Pyrdacor/Ambermoon.net#302] opened 2022-03-06 20:37 UTC
**Describe the bug**
If you use magic to fight against the Gizzeks in Dorina's tree, the game stucks when the damage is to be shown. It might be possible that perhaps one or two Gizzeks will get killed, but it never get's through all Gizzek's and the game cannot be used any longer. Only restart is possible

**To Reproduce**
1. Go to Dorina's tree
2. Fight against the Gizzeks
3. Let Nelvin use Ice-Shower Spell
4. At displaying the damage to the Gizzeks at some of the Gizzeks the game stuck

**Expected behavior**
Avery Gizzek should reveal any damage or should block the spell.

**Screenshots**
Selecting spell for the fight
![party-attacking-gizzek](https://user-images.githubusercontent.com/98125920/156941138-a574a63a-9706-43ad-aaf1-a0e9bd5c6dd4.png)
The two first Gizzeks wer keilld, but then the game stucks
![stuck-after-spell](https://user-images.githubusercontent.com/98125920/156941140-05b219dd-f69c-46db-84ee-de12fc5b5162.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Version 1.5.1

**Additional context**
It's a savegame created with 1.4.1 and now used with 1.5.1
In 9 tries I had one success in retrieve all damage and the game continue
[Save.20.zip](https://github.com/Pyrdacor/Ambermoon.net/files/8217964/Save.20.zip)
d

**Comment by Pyrdacor** [comment] 2022-03-06 20:51
Thanks for reporting. You are the third one to report this but everyone had the issue at different locations and I couldn't reproduce this yet on my end. Can you provide a savegame so I can test it? Thanks.

**Comment by Pyrdacor** [comment] 2022-03-07 08:49
Some questions:

- Did the next Gizzek (which is still alive) block the spell by any chance?
  - If so, was there a message and deflect animation already? Or one of them only?

**Comment by HptmKarotte** [comment] 2022-03-09 20:24
I just tried it another time. The message for blocking the spell slightly appears, but not the animation. Another thing that might be important is the fight speed. I made some tests and I can only reproduce it with speed +100%.
I added my savegame. It is done directly before the fight with the Gizzeks

**Comment by sisch** [comment] 2022-05-24 11:46
I haven't read the comments here, but after the comments, it seems #306 is a duplicate of this one

**Closed** 2022-06-12 21:02 UTC
Labels: bug
