### ISSUE TITLE
[Bug report] Amount of Gold not shown correctly in Chest

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#320] opened 2022-08-08 17:17 UTC
**Describe the bug**
In Dungeons the amount of gold in chests is not shown correctly. It is correctly shown when you open the chest the first time. Upon revisiting the chest the amount of gold is not shown anymore. It is shown again if you enter any characters inventory.
Same applies for food rations.

**To Reproduce**
1. Open any chest in a dungeon
2. Leave chest
3. Revisit chest
4. See described error

**Expected behavior**
The amount of gold in the chest should be shown everytime.

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/69513157/183475538-fdfafd37-8572-49f0-be09-b905038b8bbb.png)

![Screenshot_1](https://user-images.githubusercontent.com/69513157/183478095-c85e1048-d093-4842-b51f-f12c50e988c1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: ambermoon.net 1.7.01, German Ambermoon 1.17

**Comment by Pyrdacor** [comment] 2022-11-16 14:38
Hm I can't reproduce this at the moment but I can't rule out that I already fixed this at some point.

**Comment by Pyrdacor** [comment] 2022-11-16 14:40
Do you remember which chests that was?

**Comment by Thallyrion** [comment] 2022-11-16 17:13
I think I encountered this either in the Orc Caves or in the temple of Gala.

**Comment by Pyrdacor** [comment] 2022-12-06 12:30
I tried to reproduce this with the chests there but it works without problems.

**Comment by Pyrdacor** [comment] 2022-12-09 05:34
I will close this as it might have been fixed. If it occurs with the upcoming 1.8 version, feel free to reopen.

**Closed by Pyrdacor** 2022-12-09 05:34 UTC
Labels: bug, investigate
