### ISSUE TITLE
Wrong tile blocking in 2D Movement

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#40] opened 2020-09-19 09:39 UTC
v1.1.8. introduced some blocking issues in 2D Movement. 

See Video

https://drive.google.com/file/d/1E9CM3XWtyu2yl2AgnM4htfl9snw9o5eV/view?usp=sharing

**Comment by Pyrdacor** [comment] 2020-09-21 15:15
Can't reproduce with 1.1.8. How did you do this? Can you reproduce this somehow?

**Comment by Thallyrion** [comment] 2020-09-21 15:37
can't tell you more than you can see in the video. I get this behaviour when i enter Grandfather's house or the Thieves Hideout but entering buildings in Spannenberg works interestingly.

**Comment by Thallyrion** [comment] 2020-09-21 16:25
Found it! This blocked behaviour happens if you enter a 2D map while riding a horse, which should be impossible. See other issue i posted. If you enter normally everything is fine.

**Comment by Pyrdacor** [comment] 2020-09-21 20:52
Ok that makes sense. I guess the game thinks you still are on a horse and the tiles are not passable by horse. I changed it already so you can't enter buildings or water with horse. Will come in next release and should fix this too. I'll close this and we track progress in #41

**Closed by Pyrdacor** 2020-09-21 20:52 UTC
