### ISSUE TITLE
[Bug report] Color scheme seems strange in some cases after quicktravel

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#369] opened 2023-12-29 08:46 UTC
**Describe the bug**
In some cases after quick travel (I think when the time changes to 20:00 during quick travel) the 3D map is colored magenta.

**To Reproduce**
1. Quick travel to the city exit in the attached save
2. The city exit is colored in a hue of magenta (the discoloration disappears after 5 ingame minutes)

**Expected behavior**
The coloring is correct.

**Screenshots**
Before Screenshot:
![image](https://github.com/Pyrdacor/Ambermoon.net/assets/88923192/6d515e4e-4859-479e-b937-6e6c3adff691)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.9.4 / Ambermoon Advanced 1.3

**Additional context**
I attached a save where I can reproduce the bug by simply jumping to the city exit of burnville. It's the third save game in the attached folder.
[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/13795141/Saves.zip)

**Comment by Pyrdacor** [comment] 2023-12-29 14:33
Thanks I encountered it very recently as well but couldn't reproduce it. Maybe it is really about the time as different times change the palette in cities. Will try to reproduce and fix it.

**Comment by Talmit** [comment] 2023-12-29 17:28
I just noticed that github didn't attach my saves (probabilty due to ScriptSafe), so I went to a city and tried to reproduce it. Reproducing it this way worked without an issue, so the file is now attached in the original post (Save 3). This can also be used to reproduce the other two issues I opened.

**Comment by Talmit** [comment] 2023-12-29 17:31
And by the way, thanks again for all the hard work. The quality of the remake is amazing, the issues I found are mainly cosmetic in nature and do not actually impact the game play in a noticeable way. I'm always happy to play this amazing game.

**Comment by Pyrdacor** [comment] 2024-01-04 12:19
I found the issue and fixed it on my end. Will be part of the next release.

**Comment by Pyrdacor** [comment] 2024-01-06 10:53
Fixed in 1.9.5

**Closed by Pyrdacor** 2024-01-06 10:53 UTC
Labels: bug, fixed in code or data
