### ISSUE TITLE
Crash on 3D Map

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#42] opened 2020-09-19 09:47 UTC
Surprisingly i had this crash. Cannot exactly pinpoint it but it happend after entering Spannenberg and right clicking on the movement menu.

Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ambermoon.MapExtensions.TriggerEvents(Map map, Game game, IRenderPlayer player, MapEventTrigger trigger, UInt32 x, UInt32 y, IMapManager mapManager, UInt32 ticks)
   at Ambermoon.Game.TriggerMapEvents(MapEventTrigger trigger, UInt32 x, UInt32 y)
   at Ambermoon.Game.TriggerMapEvents(MapEventTrigger trigger)
   at Ambermoon.UI.Layout.<UpdateLayoutButtons>b__62_3()
   at Ambermoon.UI.Button.ExecuteActions(UInt32 currentTicks)
   at Ambermoon.UI.Button.LeftMouseDown(Position position, Nullable`1& cursorType, UInt32 currentTicks)
   at Ambermoon.UI.ButtonGrid.MouseDown(Position position, MouseButtons mouseButtons, Nullable`1& newCursorType, UInt32 currentTicks)
   at Ambermoon.UI.Layout.Click(Position position, MouseButtons buttons, CursorType& cursorType, UInt32 currentTicks)
   at Ambermoon.Game.OnMouseDown(Position position, MouseButtons buttons)
   at Ambermoon.GameWindow.Mouse_MouseDown(IMouse mouse, MouseButton button)
   at Silk.NET.Input.Desktop.GlfwMouse.HandleMouseDown(IMouse mouse, MouseButton button)
   at Silk.NET.GLFW.XC9BB5C31.Glfw.PollEvents()
   at Silk.NET.Windowing.Desktop.GlfwWindow.DoEvents()
   at Silk.NET.Windowing.Common.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Desktop.GlfwWindow.Run(Action onFrame)
   at Silk.NET.Windowing.Common.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()

**Comment by Pyrdacor** [comment] 2020-09-21 15:14
Hm can't reproduce the error.

**Comment by Thallyrion** [comment] 2020-09-21 15:34
unfortunately i can't either. I tried but i only got it once.

**Comment by Pyrdacor** [comment] 2020-09-21 20:57
The stack trace reveals that the exception was caused by a left click on the buttons. As an event is triggered by that I guess it's a click on eye, hand or mouth button. Maybe the right click switched from movement arrow to those buttons and you immediately clicked left on them.

**Comment by Pyrdacor** [comment] 2020-11-01 18:37
I will close this until the bug occurs again.

**Closed by Pyrdacor** 2020-11-01 18:37 UTC
Labels: bug
