### ISSUE TITLE
Crash on 2D Worldmap

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#6] opened 2020-08-18 11:59 UTC
I was walking around the worldmap near Spannenberg when a crash occured:

Unhandled exception. Ambermoon.AmbermoonException: [Render] Invalid index
   at Ambermoon.Renderer.RenderBuffer.GetDrawIndex(ISurface3D surface)
   at Ambermoon.Renderer.RenderLayer.GetDrawIndex(ISurface3D surface)
   at Ambermoon.Renderer.OpenGL.Surface3D.AddToLayer()
   at Ambermoon.Renderer.OpenGL.Surface3D.set_Visible(Boolean value)
   at Ambermoon.Render.RenderMap3D.AddObject(ISurface3DFactory surfaceFactory, IRenderLayer layer, UInt32 mapX, UInt32 mapY, Object obj)
   at Ambermoon.Render.RenderMap3D.UpdateSurfaces()
   at Ambermoon.Render.RenderMap3D.SetMap(Map map, UInt32 playerX, UInt32 playerY, CharacterDirection playerDirection)
   at Ambermoon.Game.Start3D(Map map, UInt32 playerX, UInt32 playerY, CharacterDirection direction)
   at Ambermoon.Render.Character2D.MoveTo(Map map, UInt32 x, UInt32 y, UInt32 ticks, Boolean frameReset, Nullable`1 newDirection)
   at Ambermoon.Render.Player2D.Move(Int32 x, Int32 y, UInt32 ticks, Nullable`1 prevDirection, Boolean updateDirectionIfNotMoving)
   at Ambermoon.Game.Move()
   at Ambermoon.GameWindow.Keyboard_KeyDown(IKeyboard keyboard, Key key, Int32 value)
   at Silk.NET.GLFW.XC6DECC54.Glfw.PollEvents()
   at Silk.NET.Windowing.Desktop.GlfwWindow.DoEvents()
   at Silk.NET.Windowing.Common.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Desktop.GlfwWindow.Run(Action onFrame)
   at Silk.NET.Windowing.Common.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()

Version 1.09
I could not reproduce it. Occured only once.

Edit: Could reproduce the crash. It randomly occurs on entering another 3D locations. In this case the Orc Caves/Burnville Tunnel
Edit2: I don't know if this actually is an issue (could not be implemented yet) not all 3D location are visitable. E.g. entering Sylph/Gala Temple  does not work. And in Spannenberg you have no Sky textures, background is just Black.

**Comment by Metibor** [comment] 2020-08-18 13:19
This is already fixed in https://github.com/Pyrdacor/Ambermoon.net/pull/5 and should be available in the next build.
With v1.09 you are only able to visit one 3D map.

**Comment by Pyrdacor** [comment] 2020-08-18 13:48
Will release the fixed version later. ;)

**Comment by Thallyrion** [comment] 2020-08-18 15:31
> This is already fixed with #5 and should be available in the next build.

Thought the 1.09 was  the fixed version as the graphic glitches in Spannenberg were gone

> With v1.09 you are only able to visit one 3D map.
This is definately not true. I was able to visit multiple 3D maps with every version including 1.09 . Only with 1.09 it crashed sometimes.

**Comment by Pyrdacor** [comment] 2020-08-18 16:54
> > This is already fixed with #5 and should be available in the next build.
> 
> Thought the 1.09 was the fixed version as the graphic glitches in Spannenberg were gone
> 

It should have been but there was a new bug caused by the fix.

> > With v1.09 you are only able to visit one 3D map.
> 
> This is definately not true. I was able to visit multiple 3D maps with every version including 1.09 . Only with 1.09 it crashed sometimes.

I think he meant visiting without bugs. As I mentioned above a new bug with introduced with the fix. It is also fixed but there is no release with that fix yet. But soon. ;)

**Comment by Pyrdacor** [comment] 2020-08-18 19:29
This should be fixed in v1.0.10. :)

**Comment by Thallyrion** [comment] 2020-08-18 20:10
Crash seems to be fixed. Walked all over the map and entered every 3D map multiple time. No crash.

**Comment by Pyrdacor** [comment] 2020-08-18 20:14
Nice. I'll close this issue.

**Closed by Pyrdacor** 2020-08-18 20:14 UTC

**Comment by Thallyrion** [comment] 2020-08-29 10:52
Hi

v1.0.14 download is not working. File is not found.

Am Di., 18. Aug. 2020 um 22:14 Uhr schrieb Pyrdacor <
notifications@github.com>:

**Comment by Pyrdacor** [comment] 2020-08-29 10:55
Thank you. Should be there now.
