### ISSUE TITLE
trader selling multiple items

### ISSUE THREAD

**Issue by Shinhobi** [Pyrdacor/Ambermoon.net#97] opened 2021-07-15 03:18 UTC
when trying to sell a greater number than 1 of an item it does not work. the counter won't go higher than 1.

**Comment by Pyrdacor** [comment] 2021-07-15 07:16
Hm I have no problems with that. What specific trader and item did you test? Do you have a savegame so I can check?

**Comment by Pyrdacor** [comment] 2021-07-16 19:27
@Shinhobi Can you provide more info about the issue please? I can't reproduce it.

**Comment by Shinhobi** [comment] 2021-07-16 19:57
will try as soon as i can. i tested again and it worked this time..

Pyrdacor ***@***.***> schrieb am Fr., 16. Juli 2021, 21:27:

**Comment by Uukrull** [comment] 2021-07-16 20:15
This happens with some items (padded leather, shortsword, shortbow...)

![4](https://user-images.githubusercontent.com/5891591/126003449-bff459b4-3463-4029-8e2f-1df41fde3795.png)

You can't select more than 1:

![5](https://user-images.githubusercontent.com/5891591/126003505-954e8089-4553-4c79-8884-8a3592cb0ca5.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6833150/Saves.zip)

**Comment by Pyrdacor** [comment] 2021-07-17 09:03
Ah I guess with items that can't be stacked normally and only at traders. Will have a look and fix it. Thanks for the investigation.

**Comment by Shinhobi** [comment] 2021-07-17 10:27
well, good to hear that riddle is solved

**Comment by Pyrdacor** [comment] 2021-07-19 06:00
Ok the problem was another one. You shouldn't be able to stack armor or weapons in the first place. So you won't be able to sell a stack of those items at all. I found the cause: If you drop items from somewhere onto a player portrait (which you do if you buy stuff or loot a chest) they would stack even if the item is not stackable. I removed this bug so that they won't stack anymore.

To allow progressing with saves which had this bug I also eased the restriction on the "amount box" so you should be able to sell multiple items as well.

**Comment by Pyrdacor** [comment] 2021-07-19 06:00
Release will be updated later.

**Comment by Pyrdacor** [comment] 2021-07-19 09:31
Should be fixed. Just download the test release again. ;)

**Closed by Pyrdacor** 2021-07-19 09:31 UTC
Labels: bug, v1.0

**Comment by Uukrull** [comment] 2021-07-19 11:00
> Ok the problem was another one. You shouldn't be able to stack armor or weapons in the first place.

I thought that was a feature of the remake :) Having the weight limit AND the slots limit in the original is a PITA.

**Comment by Pyrdacor** [comment] 2021-07-19 11:32
Sorry but I want the remake to be as close as possible to the original. At least game logic wise.

And it is even more simple to change this in the original data because you can specify the "stackable" flag for each item as you wish. So I would add this to a mod which is also available on Amiga where all items are stackable.
